### ISSUE TITLE
[Feat]: Next Gen Support

### ISSUE THREAD

**Issue by abstract-base-method** [harness/backstage-plugins#89]
## 🔖 Feature description

The API still implements against the current generation Harness API, even though clients are being told in the CD UI to migrate to next gen. 

## 🎤 Context

This would make it such that customers who have already migrated or started on next-gen would be able to leverage the Harness module

## ✌️ Possible Implementation

I think having a separate component would be best, that way you could support both at the same time with some minimal tweaks to the API calls themselves.

**Comment by OrkoHunter** [comment]
Hey @abstract-base-method, the plugin already supports Next Gen and we have built it for next gen only. What error did you receive when integrating with it?

**Comment by OrkoHunter** [comment]
Didn't hear from you @abstract-base-method. Will close this now.
